// Code generated by MockGen. DO NOT EDIT.
// Source: ./parser.go

// Package parser is a generated GoMock package.
package parser

import (
	structs "github.com/g3co/ticket-sorter/structs"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockParser is a mock of IParser interface
type MockParser struct {
	ctrl     *gomock.Controller
	recorder *MockParserMockRecorder
}

// MockParserMockRecorder is the mock recorder for MockParser
type MockParserMockRecorder struct {
	mock *MockParser
}

// NewMockParser creates a new mock instance
func NewMockParser(ctrl *gomock.Controller) *MockParser {
	mock := &MockParser{ctrl: ctrl}
	mock.recorder = &MockParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockParser) EXPECT() *MockParserMockRecorder {
	return m.recorder
}

// Parse mocks base method
func (m *MockParser) Parse(card string) (*structs.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", card)
	ret0, _ := ret[0].(*structs.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse
func (mr *MockParserMockRecorder) Parse(card interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockParser)(nil).Parse), card)
}
